wandb_version: 1

data__categorical:
  value: 'false'
data__keyword:
  value: 361055
data__method_name:
  value: openml_no_transform
data__regression:
  value: 'false'
max_test_samples:
  value: 36932
max_train_samples:
  value: 15374
max_val_samples:
  value: 57323
model__args__batch_size:
  value: 82
model__args__data_parallel:
  value: 'false'
model__args__early_stopping_rounds:
  value: 11
model__args__epochs:
  value: 583
model__args__lr:
  value: 1.5097772193834067e-05
model__args__model_name:
  value: saint
model__args__num_classes:
  value: 1
model__args__objective:
  value: regression
model__args__use_gpu:
  value: 'true'
model__args__val_batch_size:
  value: 216
model__params__depth:
  value: 2
model__params__dim:
  value: 86
model__params__dropout:
  value: 0.06816526671262135
model__params__heads:
  value: 2
model_name:
  value: saint
model_type:
  value: tab_survey
n_iter:
  value: auto
regression:
  value: 'false'
train_prop:
  value: 1.17482157976413
transform__0__apply_on:
  value: numerical
transform__0__method_name:
  value: gaussienize
transform__0__type:
  value: quantile
transformed_target:
  value: 'true'
use_gpu:
  value: 'true'
val_test_prop:
  value: 0.19391753167032968
