wandb_version: 1

data__categorical:
  value: 'false'
data__keyword:
  value: 361066
data__method_name:
  value: openml_no_transform
data__regression:
  value: 'false'
max_test_samples:
  value: 62193
max_train_samples:
  value: 18406
max_val_samples:
  value: 61692
model__args__batch_size:
  value: 221
model__args__data_parallel:
  value: 'false'
model__args__early_stopping_rounds:
  value: 14
model__args__epochs:
  value: 369
model__args__lr:
  value: 4.990188762046152e-05
model__args__model_name:
  value: saint
model__args__num_classes:
  value: 2
model__args__objective:
  value: regression
model__args__use_gpu:
  value: 'false'
model__args__val_batch_size:
  value: 185
model__params__depth:
  value: 4
model__params__dim:
  value: 203
model__params__dropout:
  value: 0.08276226182091509
model__params__heads:
  value: 3
model_name:
  value: saint
model_type:
  value: tab_survey
n_iter:
  value: auto
regression:
  value: 'true'
train_prop:
  value: 1.133418452696847
transform__0__apply_on:
  value: numerical
transform__0__method_name:
  value: gaussienize
transform__0__type:
  value: quantile
transformed_target:
  value: 'true'
use_gpu:
  value: 'false'
val_test_prop:
  value: 0.3336965433944538
