wandb_version: 1

data__categorical:
  value: 'true'
data__keyword:
  value: 361066
data__method_name:
  value: openml_no_transform
data__regression:
  value: 'true'
max_test_samples:
  value: 43482
max_train_samples:
  value: 11441
max_val_samples:
  value: 94683
model__args__batch_size:
  value: 225
model__args__data_parallel:
  value: 'true'
model__args__early_stopping_rounds:
  value: 20
model__args__epochs:
  value: 581
model__args__lr:
  value: 4.30841103815783e-05
model__args__model_name:
  value: saint
model__args__num_classes:
  value: 1
model__args__objective:
  value: regression
model__args__use_gpu:
  value: 'true'
model__args__val_batch_size:
  value: 232
model__params__depth:
  value: 6
model__params__dim:
  value: 119
model__params__dropout:
  value: 0.191552477522673
model__params__heads:
  value: 4
model_name:
  value: saint
model_type:
  value: tab_survey
n_iter:
  value: auto
regression:
  value: 'false'
train_prop:
  value: 0.6794679534426179
transform__0__apply_on:
  value: numerical
transform__0__method_name:
  value: gaussienize
transform__0__type:
  value: quantile
transformed_target:
  value: 'false'
use_gpu:
  value: 'true'
val_test_prop:
  value: 0.4006784230141561
