wandb_version: 1

data__categorical:
  value: 'false'
data__keyword:
  value: 361066
data__method_name:
  value: openml_no_transform
data__regression:
  value: 'true'
max_test_samples:
  value: 66044
max_train_samples:
  value: 15626
max_val_samples:
  value: 59054
model__args__batch_size:
  value: 225
model__args__data_parallel:
  value: 'true'
model__args__early_stopping_rounds:
  value: 7
model__args__epochs:
  value: 255
model__args__lr:
  value: 5.61393740881475e-05
model__args__model_name:
  value: saint
model__args__num_classes:
  value: 2
model__args__objective:
  value: regression
model__args__use_gpu:
  value: 'true'
model__args__val_batch_size:
  value: 126
model__params__depth:
  value: 2
model__params__dim:
  value: 78
model__params__dropout:
  value: 0.12747527968067962
model__params__heads:
  value: 6
model_name:
  value: saint
model_type:
  value: tab_survey
n_iter:
  value: auto
regression:
  value: 'true'
train_prop:
  value: 0.7325958380690263
transform__0__apply_on:
  value: numerical
transform__0__method_name:
  value: gaussienize
transform__0__type:
  value: quantile
transformed_target:
  value: 'false'
use_gpu:
  value: 'false'
val_test_prop:
  value: 0.555382959871645
