wandb_version: 1

data__categorical:
  value: 'true'
data__keyword:
  value: 44126
data__method_name:
  value: openml_no_transform
data__regression:
  value: 'true'
max_test_samples:
  value: 42653
max_train_samples:
  value: 5459
max_val_samples:
  value: 97189
model__args__batch_size:
  value: 118
model__args__data_parallel:
  value: 'false'
model__args__early_stopping_rounds:
  value: 10
model__args__epochs:
  value: 540
model__args__lr:
  value: 5.7077843434483675e-05
model__args__model_name:
  value: saint
model__args__num_classes:
  value: 2
model__args__objective:
  value: regression
model__args__use_gpu:
  value: 'true'
model__args__val_batch_size:
  value: 195
model__params__depth:
  value: 4
model__params__dim:
  value: 229
model__params__dropout:
  value: 0.1328976043569149
model__params__heads:
  value: 8
model_name:
  value: saint
model_type:
  value: tab_survey
n_iter:
  value: auto
regression:
  value: 'false'
train_prop:
  value: 0.4043440517259185
transform__0__apply_on:
  value: numerical
transform__0__method_name:
  value: gaussienize
transform__0__type:
  value: quantile
transformed_target:
  value: 'false'
use_gpu:
  value: 'false'
val_test_prop:
  value: 0.5360203821983933
