wandb_version: 1

data__categorical:
  value: 'false'
data__keyword:
  value: 44126
data__method_name:
  value: openml_no_transform
data__regression:
  value: 'false'
max_test_samples:
  value: 85594
max_train_samples:
  value: 8404
max_val_samples:
  value: 35586
model__args__batch_size:
  value: 118
model__args__data_parallel:
  value: 'false'
model__args__early_stopping_rounds:
  value: 17
model__args__epochs:
  value: 236
model__args__lr:
  value: 4.6905303008140266e-05
model__args__model_name:
  value: saint
model__args__num_classes:
  value: 2
model__args__objective:
  value: regression
model__args__use_gpu:
  value: 'false'
model__args__val_batch_size:
  value: 149
model__params__depth:
  value: 6
model__params__dim:
  value: 81
model__params__dropout:
  value: 0.0905235914474659
model__params__heads:
  value: 8
model_name:
  value: saint
model_type:
  value: tab_survey
n_iter:
  value: auto
regression:
  value: 'false'
train_prop:
  value: 0.5413430271499592
transform__0__apply_on:
  value: numerical
transform__0__method_name:
  value: gaussienize
transform__0__type:
  value: quantile
transformed_target:
  value: 'false'
use_gpu:
  value: 'false'
val_test_prop:
  value: 0.32862608908693947
